--- 
title: "NYC Crime"
author: "Group 32: Abhiram Gaddam, Faizan Dogar, Devan Samant"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction



#Outline/Work/Notes
Introduction - "Explain why you chose this topic, and the questions you are interested in studying. Provide context for readers who are not familiar with the topic."
  
Data
  copy proposal wording back into data section
  --Focus: Just around Upper Manhattan (if enough data)

Profiling
  Describe any issues / problems with the data, either known or that you discover.
  NULL values - 
  Binning for dates
  Potential date mismatch of when crime happened vs when crime was reported
  Recreate some basic statistics about the data we have using bar charts or whatever
  Google to see how others used dataset
      https://towardsdatascience.com/analysis-of-nyc-reported-crime-data-using-pandas-821753cd7e22
      https://www.kaggle.com/datasets/adamschroeder/crimes-new-york-city
      https://jingjing-ge.medium.com/analysis-of-crime-data-in-new-york-city-in-2020-e6a65edf4429
      https://www.kaggle.com/code/spoons/nyc-crime-complaints-guided-eda-with-shiny-app
    

Data Cleaning
  need a metric count of crimes
  derived field of the distance from morningside park center to the row's coordinate (ie. radius nearby --need another package)
  derived field about the severity or relcassify crime - (ex parking tickets). To reduce distinct number down to something managble.
  derive day of week from the datetime field
  date cleanups using data dictionary and maybe some assumptions so that we have a more accurate point in time (just use start) 
  

Results / Graph Ideas
  Univariate/Multivariate Categorical Ideas:
      crime frequency vs gender/age group/borough --maybe bar charts or mosaics
      
  Continuous Variable Ideas:
    (Interactive) changing radius from (morningside) park to see impact on crime rate density (frequency/area of radius)
    Time series (over months/days of week)  - look at changes over time/seasonality
      (interactive) - control time lapse of heatmap of NYC or something
    Time (during the day) - 
  
  Map: 
  
  
#Tasks
1. Get coordinates data for a specific location and use that calculate the distance from each complaint --Faizan
2. We need to assign categories to crimes --Abhi
3. Look into how best to use the time variables for various time series analyses
4. General exploration of data (via online viz or R) / take notes on missing value cleanup/interesting findings --All






    
