# Results


```{r}
#What Graphs Do We Want?

#Data Prep Graphs
#1) Missing data patterns by row (using redav library or mi library) --heatmap


#Demographic Related Chart
#1) Bar Chart - CRIME_CAT by VIC Gender and/or SUSPECT Gender
#2) Mosaic Plot - TBD (CRIME CAT, VIC Gender, and Premise, +)
#3) Count by Premise (or use as a cut)
#--see ideas below

#Time Series Charts
#1) Line Chart - Overall 2022 Trend by Count
#2) Bar Chart - CRIME CAT by Day of Week
#3) Density Plot - Count by Time of Day (maybe with facets)
#4) (TBD more CRIME CAT by Time or Premise by Time of Day/Park)
#5) Look at box plot by time of day?

#Maps & Distance Info
#1) Counts By Borough (bar chart) (consider faceting by another dimension that looks good)
#2) Map of count in Columbia Area
#3) Line Graph of Density At Diff Points (x is distance from CU and y is total counts)
#4) Heat Map/Choropleth - Count by Precinct Code (may require addl data? --look into if feasible)

#Other Potential
#x) Parallel Coordinates Plot - not enough continuous vars
#x) Stacked Bar Chart?
#x) Scatter Plot (of Distance from CU vs Time of Day?)
#x) Cleveland Dot Plot - TBD

```



```{r}
agg_tbl <- df_filter %>% group_by(CRIME_CAT) %>% 
  summarise(total_count=n(),
            .groups = 'drop')
df_counts <- agg_tbl %>% as.data.frame()

plt <- ggplot(df_counts) + geom_bar(aes(y=CRIME_CAT, x=total_count), stat="identity")
plt
```

